version: '3.7'
services:
  group_control_db:
    image: postgres:11.6
    container_name: group_control_db
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=group_control
    ports:
      - 5432:5432
    volumes:
      - postgresdata:/var/lib/postgresql/data

volumes:
  postgresdata:
